name = "v20251104"
main = "_worker.js"
compatibility_date = "2026-01-20"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

# KV 命名空间绑定（必须绑定为 KV）
kv_namespaces = [
  { binding = "KV", id = "" }
]

# 环境变量默认值
[vars]
ADMIN = ""
UUID = "882f758d-3436-4f85-a79f-34c00e20a151"

# 触发器规则
[triggers]
crons = []
